[package]
name = "rlpcli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.34"
lesspass = "~0.2"
log = "~0.4"
env_logger = "~0.9"
reqwest = { version = "~0.11", features = ["json"] }
ring = "~0.13"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
url = "~2.2"
xdg = "~2.4"
