[package]
name = "rlpcli"
version = "0.3.0"
authors = ["Óscar García Amor <ogarcia@connectical.com>"]
edition = "2021"
description = "CLI helper to get paswords and site settings directly from a LessPass server"
readme = "README.md"
repository = "https://github.com/ogarcia/rlpcli"
license = "GPL-3.0-only"
keywords = ["lesspass", "rockpass", "password", "client", "cli"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "~4.0", features = ["cargo"] }
lesspass = "~0.4"
log = "~0.4"
env_logger = "~0.10"
serde = { version = "~1.0", features = ["derive"] }
ureq = { version = "~2.6", features = ["json"] }
url = "~2.3"
xdg = "~2.4"
