[package]
name = "rlpcli"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "~4.0", features = ["cargo"] }
lesspass = "~0.4"
log = "~0.4"
env_logger = "~0.10"
reqwest = { version = "~0.11", features = ["json"] }
serde = { version = "~1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
url = "~2.3"
xdg = "~2.4"
